name: pytorch_lite_example
description: Demonstrates how to use the pytorch_lite plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  pytorch_lite: ^4.3.2
  image_picker: ^1.1.2
  path_provider: ^2.0.2
  camera: ^0.11.0+2
  image: ^4.0.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
      sdk: flutter
  flutter_driver:
      sdk: flutter 
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/labels/